name: build-guestfs

on:
  push:
    tags:
      - "guestfs"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
        platform: [linux]
    steps:
      - name: Branch name
        id: branch_name
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: setup-qemu-action
        uses: docker/setup-qemu-action@v1

      - name: Build in docker
        run: |
          docker run --entrypoint /bin/sh --name guestfs --platform linux/${{ matrix.arch }} -v ${PWD}:/app alpine:3.15 -c "apk add g++ && \
          cd /app && \
          g++ unmount.cpp -std=c++17 -I./ -o unmount && \
          g++ guestfs.cpp -std=c++17 -I./ -o guestfs && \
          g++ guestexec.cpp -std=c++17 -I./ -o guestexec && \
          chmod +x guestfs && \
          ./guestfs"

          sudo docker cp guestfs:/app/unmount ./unmount-${{ matrix.arch }}
          sudo docker cp guestfs:/app/guestfs ./guestfs-${{ matrix.arch }}
          sudo docker cp guestfs:/app/guestexec ./guestexec-${{ matrix.arch }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            unmount-${{ matrix.arch }}
            guestfs-${{ matrix.arch }}
            guestexec-${{ matrix.arch }}
          prerelease: true