name: build-guestfs

on:
  push:
    tags:
      - "guestfs"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
        platform: [linux]
    steps:
      - name: Branch name
        id: branch_name
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: setup-qemu-action
        uses: docker/setup-qemu-action@v1

      - name: Build in docker
        run: |
          docker run --entrypoint /bin/sh --name guestfs --platform linux/${{ matrix.arch }} -v ${PWD}:/app alpine -c "pwd && \
          cd /root/ && \ 
          apk update && \
          apk add git python3 make ninja gcc g++ musl-dev pkgconfig glib-dev pixman-dev perl && \
          g++ guestfs.cpp -o guestfs"

          sudo docker cp guestfs:/root/guestfs ./guestfs-${{ matrix.arch }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            guestfs-${{ matrix.arch }}
          prerelease: true